### ISSUE TITLE
Indicate root path for serverless.yml to support multiple serverless deploy

### ISSUE THREAD

**Issue by alex-piccione** [SuprGames/serverless-github-action#2]
Imagine a GitHub action within 2 different serverless.yml files stored in:
- ./project one/serverless.yml
- ./project two/serverless.yml

At the moment it is possible to run the ``deploy`` command on both with something like:
```yml
jobs:
  deploy:
    steps: 
    - name: Serverless C# project
      uses: serverless/github-action@master
      with:        
        args: deploy --config "./project one/serverless.yml"
    - name: Serverless Python project
      uses: serverless/github-action@master
      with:        
        args: deploy --config "./project two/serverless.yml"
```
Using ``--config`` parameter gives a warning that says that it will not be supported in the next major release and ``serverless.yml`` can only exists in the root path of the project.  
That means you cannot  use multiple ones.  
I want to use multiple ones because I need multiple serverless Services with different Provider runtimes (for example  python3.8 and Net)
